var mongoose = require('mongoose');

var reviewSchema = mongoose.Schema({
    placeid: {type: String, required: true},
    email: {type: String},
    name: {type: String},
    rating: {type: Number},
    review: {type: String},
    date: {type: Date},
    arty: {type: String},
    design: {type: String},
    authentic: {type: String},
    brunch: {type: String},
    cocktails: {type: String},
    food: {type: String},
    dogs: {type: String},
    elegant: {type: String},
    entertaining: {type: String},
    beer: {type: String},
    family: {type: String},
    service: {type: String},
    wines: {type: String},
    portions: {type: String},
    glamorous: {type: String},
    groups: {type: String},
    atmosphere: {type: String},
    meetings: {type: String},
    music: {type: String},
    healthy: {type: String},
    intimate: {type: String},
    lgbtq: {type: String},
    modern: {type: String},
    party: {type: String},
    popup: {type: String},
    quirky: {type: String},
    relaxed: {type: String},
    romantic: {type: String},
    rustic: {type: String},
    vegan: {type: String},
    vegetarian: {type: String}
});

module.exports = mongoose.model('Review', reviewSchema);
